//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPWBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPWBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blood_diamond_knuckles.png
        ///blessed_sais.png
        ///descent_armor.png
        ///coral_katana.png
        ///deception_mail.png
        ///tortise_plate.png
        ///vampire_sword.png
        ///cursed_rapier.png
        ///zealand_sword.png
        ///sun_dagger.png
        ///hell_blade.png
        ///fathom_staff.png.
        /// </summary>
        internal static string BlacklistedItems {
            get {
                return ResourceManager.GetString("BlacklistedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psilocybin_band.png
        ///blackops_issue.png
        ///ibot.png
        ///clergy_book.png
        ///year_of_the_plague.png
        ///sneakerology_limited.png
        ///monacle_pocket_watch.png
        ///cascade_kicks.png
        ///zissou_gas_mask.png
        ///robo_bot.png
        ///howie_farers.png
        ///shadow_ribbon.png
        ///hurricane_kicks.png
        ///kicks.png
        ///ruby_ring.png
        ///emerald_ring.png
        ///tribal_mask2.png
        ///sapphire_ring.png
        ///green_wayfarers.png
        ///thief_beanie.png
        ///nuclear_gas_mask.png
        ///spellbook.png
        ///rainbow_beanie.png
        ///blue_ribbon.png
        ///orange_wayfarers.png
        ///fuschia_wayfarers.png
        ///tribal_mask1.png        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhitelistedItems {
            get {
                return ResourceManager.GetString("WhitelistedItems", resourceCulture);
            }
        }
    }
}
