// <auto-generated />

namespace EPWBot
{
    /// <summary>
    /// Main user interface to the bot
    /// </summary>
    public partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.WebBrowser = new System.Windows.Forms.WebBrowser();
            this.ActionTimer = new System.Windows.Forms.Timer(this.components);
            this.UserName = new System.Windows.Forms.TextBox();
            this.Password = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.Start = new System.Windows.Forms.Button();
            this.TableLayout = new System.Windows.Forms.TableLayoutPanel();
            this.PlayerStatsGroupBox = new System.Windows.Forms.GroupBox();
            this.RecoverHealthButton = new System.Windows.Forms.Button();
            this.MaxHp = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.Hp = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.CredentialsGroupBox = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.QueueGroupBox = new System.Windows.Forms.GroupBox();
            this.QueueListBox = new System.Windows.Forms.ListBox();
            this.label5 = new System.Windows.Forms.Label();
            this.AnimalIdTextBox = new System.Windows.Forms.TextBox();
            this.AddToQueueButton = new System.Windows.Forms.Button();
            this.TableLayout.SuspendLayout();
            this.PlayerStatsGroupBox.SuspendLayout();
            this.CredentialsGroupBox.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.QueueGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // WebBrowser
            // 
            this.WebBrowser.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WebBrowser.Location = new System.Drawing.Point(3, 3);
            this.WebBrowser.MinimumSize = new System.Drawing.Size(20, 20);
            this.WebBrowser.Name = "WebBrowser";
            this.WebBrowser.ScriptErrorsSuppressed = true;
            this.WebBrowser.Size = new System.Drawing.Size(878, 705);
            this.WebBrowser.TabIndex = 0;
            this.WebBrowser.DocumentCompleted += new System.Windows.Forms.WebBrowserDocumentCompletedEventHandler(this.WebBrowser_DocumentCompleted);
            // 
            // ActionTimer
            // 
            this.ActionTimer.Interval = 1;
            this.ActionTimer.Tick += new System.EventHandler(this.ActionTimer_Tick);
            // 
            // UserName
            // 
            this.UserName.Location = new System.Drawing.Point(90, 23);
            this.UserName.Name = "UserName";
            this.UserName.Size = new System.Drawing.Size(145, 20);
            this.UserName.TabIndex = 1;
            this.UserName.Text = "mandreko";
            // 
            // Password
            // 
            this.Password.Location = new System.Drawing.Point(90, 49);
            this.Password.Name = "Password";
            this.Password.Size = new System.Drawing.Size(145, 20);
            this.Password.TabIndex = 2;
            this.Password.Text = "fihsjh";
            this.Password.UseSystemPasswordChar = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(14, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(58, 13);
            this.label1.TabIndex = 3;
            this.label1.Text = "Username:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(16, 54);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(56, 13);
            this.label2.TabIndex = 4;
            this.label2.Text = "Password:";
            // 
            // Start
            // 
            this.Start.Location = new System.Drawing.Point(241, 49);
            this.Start.Name = "Start";
            this.Start.Size = new System.Drawing.Size(75, 22);
            this.Start.TabIndex = 5;
            this.Start.Text = "Start";
            this.Start.UseVisualStyleBackColor = true;
            this.Start.Click += new System.EventHandler(this.Start_Click);
            // 
            // TableLayout
            // 
            this.TableLayout.ColumnCount = 2;
            this.TableLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayout.Controls.Add(this.PlayerStatsGroupBox, 1, 0);
            this.TableLayout.Controls.Add(this.CredentialsGroupBox, 0, 0);
            this.TableLayout.Controls.Add(this.tableLayoutPanel1, 0, 2);
            this.TableLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayout.Location = new System.Drawing.Point(0, 0);
            this.TableLayout.Name = "TableLayout";
            this.TableLayout.RowCount = 3;
            this.TableLayout.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.TableLayout.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.TableLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 406F));
            this.TableLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayout.Size = new System.Drawing.Size(1094, 823);
            this.TableLayout.TabIndex = 0;
            // 
            // PlayerStatsGroupBox
            // 
            this.PlayerStatsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.PlayerStatsGroupBox.Controls.Add(this.RecoverHealthButton);
            this.PlayerStatsGroupBox.Controls.Add(this.MaxHp);
            this.PlayerStatsGroupBox.Controls.Add(this.label4);
            this.PlayerStatsGroupBox.Controls.Add(this.Hp);
            this.PlayerStatsGroupBox.Controls.Add(this.label3);
            this.PlayerStatsGroupBox.Location = new System.Drawing.Point(550, 3);
            this.PlayerStatsGroupBox.Name = "PlayerStatsGroupBox";
            this.PlayerStatsGroupBox.Size = new System.Drawing.Size(541, 100);
            this.PlayerStatsGroupBox.TabIndex = 7;
            this.PlayerStatsGroupBox.TabStop = false;
            this.PlayerStatsGroupBox.Text = "Player Stats";
            // 
            // RecoverHealthButton
            // 
            this.RecoverHealthButton.AutoSize = true;
            this.RecoverHealthButton.Location = new System.Drawing.Point(9, 71);
            this.RecoverHealthButton.Name = "RecoverHealthButton";
            this.RecoverHealthButton.Size = new System.Drawing.Size(117, 23);
            this.RecoverHealthButton.TabIndex = 4;
            this.RecoverHealthButton.Text = "Recover Health Now";
            this.RecoverHealthButton.UseVisualStyleBackColor = true;
            this.RecoverHealthButton.Click += new System.EventHandler(this.RecoverHealthButton_Click);
            // 
            // MaxHp
            // 
            this.MaxHp.AutoSize = true;
            this.MaxHp.Location = new System.Drawing.Point(64, 48);
            this.MaxHp.Name = "MaxHp";
            this.MaxHp.Size = new System.Drawing.Size(0, 13);
            this.MaxHp.TabIndex = 3;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(9, 49);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(48, 13);
            this.label4.TabIndex = 2;
            this.label4.Text = "Max HP:";
            // 
            // Hp
            // 
            this.Hp.AutoSize = true;
            this.Hp.Location = new System.Drawing.Point(37, 26);
            this.Hp.Name = "Hp";
            this.Hp.Size = new System.Drawing.Size(0, 13);
            this.Hp.TabIndex = 1;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(6, 26);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(25, 13);
            this.label3.TabIndex = 0;
            this.label3.Text = "HP:";
            // 
            // CredentialsGroupBox
            // 
            this.CredentialsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.CredentialsGroupBox.Controls.Add(this.Password);
            this.CredentialsGroupBox.Controls.Add(this.UserName);
            this.CredentialsGroupBox.Controls.Add(this.label1);
            this.CredentialsGroupBox.Controls.Add(this.Start);
            this.CredentialsGroupBox.Controls.Add(this.label2);
            this.CredentialsGroupBox.Location = new System.Drawing.Point(3, 3);
            this.CredentialsGroupBox.Name = "CredentialsGroupBox";
            this.CredentialsGroupBox.Size = new System.Drawing.Size(541, 100);
            this.CredentialsGroupBox.TabIndex = 6;
            this.CredentialsGroupBox.TabStop = false;
            this.CredentialsGroupBox.Text = "Login Credentials";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.TableLayout.SetColumnSpan(this.tableLayoutPanel1, 2);
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 81.25F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18.75F));
            this.tableLayoutPanel1.Controls.Add(this.QueueGroupBox, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.WebBrowser, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 109);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1088, 711);
            this.tableLayoutPanel1.TabIndex = 8;
            // 
            // QueueGroupBox
            // 
            this.QueueGroupBox.Controls.Add(this.AddToQueueButton);
            this.QueueGroupBox.Controls.Add(this.AnimalIdTextBox);
            this.QueueGroupBox.Controls.Add(this.label5);
            this.QueueGroupBox.Controls.Add(this.QueueListBox);
            this.QueueGroupBox.Location = new System.Drawing.Point(887, 3);
            this.QueueGroupBox.Name = "QueueGroupBox";
            this.QueueGroupBox.Size = new System.Drawing.Size(198, 352);
            this.QueueGroupBox.TabIndex = 0;
            this.QueueGroupBox.TabStop = false;
            this.QueueGroupBox.Text = "Queue";
            // 
            // QueueListBox
            // 
            this.QueueListBox.FormattingEnabled = true;
            this.QueueListBox.Location = new System.Drawing.Point(6, 19);
            this.QueueListBox.Name = "QueueListBox";
            this.QueueListBox.Size = new System.Drawing.Size(186, 212);
            this.QueueListBox.TabIndex = 0;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(7, 271);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(121, 13);
            this.label5.TabIndex = 1;
            this.label5.Text = "Add animal ID to queue:";
            // 
            // AnimalIdTextBox
            // 
            this.AnimalIdTextBox.Location = new System.Drawing.Point(10, 288);
            this.AnimalIdTextBox.Name = "AnimalIdTextBox";
            this.AnimalIdTextBox.Size = new System.Drawing.Size(182, 20);
            this.AnimalIdTextBox.TabIndex = 2;
            // 
            // AddToQueueButton
            // 
            this.AddToQueueButton.Location = new System.Drawing.Point(10, 315);
            this.AddToQueueButton.Name = "AddToQueueButton";
            this.AddToQueueButton.Size = new System.Drawing.Size(75, 23);
            this.AddToQueueButton.TabIndex = 3;
            this.AddToQueueButton.Text = "Add";
            this.AddToQueueButton.UseVisualStyleBackColor = true;
            this.AddToQueueButton.Click += new System.EventHandler(this.AddToQueueButton_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1094, 823);
            this.Controls.Add(this.TableLayout);
            this.MinimumSize = new System.Drawing.Size(920, 297);
            this.Name = "MainForm";
            this.Text = "EPW Bot";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.TableLayout.ResumeLayout(false);
            this.PlayerStatsGroupBox.ResumeLayout(false);
            this.PlayerStatsGroupBox.PerformLayout();
            this.CredentialsGroupBox.ResumeLayout(false);
            this.CredentialsGroupBox.PerformLayout();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.QueueGroupBox.ResumeLayout(false);
            this.QueueGroupBox.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.WebBrowser WebBrowser;
        private System.Windows.Forms.Timer ActionTimer;
        private System.Windows.Forms.TextBox UserName;
        private System.Windows.Forms.TextBox Password;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button Start;
        private System.Windows.Forms.TableLayoutPanel TableLayout;
        private System.Windows.Forms.GroupBox CredentialsGroupBox;
        private System.Windows.Forms.GroupBox PlayerStatsGroupBox;
        private System.Windows.Forms.Label Hp;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label MaxHp;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Button RecoverHealthButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.GroupBox QueueGroupBox;
        private System.Windows.Forms.Button AddToQueueButton;
        private System.Windows.Forms.TextBox AnimalIdTextBox;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.ListBox QueueListBox;
    }
}

